import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

import { gql, useQuery } from "@apollo/client";

const GET_MISSIONS = gql`
  query GetSpaceMission($limit: Int!) {
    launchesPast(limit: $limit) {
      mission_name
      launch_site {
        site_name_long
      }
      rocket {
        rocket_name
      }
      links {
        video_link
        flickr_images
      }
      ships {
        image
      }
    }
  }
`;

export default function Home() {
  const limit = 40;

  const { loading, error, data } = useQuery(GET_MISSIONS, {
    variables: { limit },
  });

  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.container}>
          {data?.launchesPast.map((launch) => {
            return <div>{launch.mission_name}</div>;
          })}
        </div>
      </main>
    </div>
  );
}
